services:
  hermes-webui-momo:
    container_name: hermes-webui-momo
    environment:
      HERMES_WEBUI_PASSWORD: REDACTED-SECRET-PURGED
      HERMES_WEBUI_STATE_DIR: /home/hermeswebui/.hermes/webui
      TZ: Asia/Shanghai
      WANTED_GID: 10000
      WANTED_UID: 10000
    image: ghcr.io/jazzzzmaybe/hermes-webui:latest
    networks:
      - shared
    ports:
      - 8787:8787
    restart: unless-stopped
    volumes:
      - /mnt/disks/Docker/hermes-momo:/home/hermeswebui/.hermes:rw
      - /mnt/disks/Docker/hermes-webui-momo/workspace:/workspace:rw

networks:
  shared:
    external: true
